### ISSUE TITLE
eom-mbpt2

### ISSUE THREAD

**Issue by pwborthwick** [jjgoings/pyqchem#1]
Hi @jjgoings ,
   I started to look at EOM and started with eom-mbpt2. Having found pychem I see you have referenced equations but you don't say to what paper they refer. I have found this paper [Steven R. Gwaltney, Marcel Nooijen, Rodney J. Bartlett Chemical Physics Letters 248 (1996) 189-198] (https://notendur.hi.is/agust/rannsoknir/papers/cpl248-189-96.pdf). In this paper 

H<sub>SS</sub> = &Sigma; F<sub>ae</sub> - &Sigma; F<sub>mi</sub> + &Sigma; W<sub>amie</sub>    (16)

F<sub>ab</sub> = f<sub>ab</sub> - 0.5 &Sigma; &tau;<sup>ae</sup><sub>mn</sub> <mn||be>                (25)

F<sub>ij</sub> = f<sub>ij</sub> - 0.5 &Sigma; &tau;<sup>ef</sup><sub>mj</sub> <im||ef>                         (26)

If these equations are correct then in your code

           for m in range(0,Nelec):
              for e in range(Nelec,dim):
                HSS[ia,kc] += ints[k,m,c,e]*td[e,a,m,i]                               # 12
                for n in range(0,Nelec):
                  HSS[ia,kc] += -0.5*(i==k)*ints[m,n,c,e]*td[a,e,m,n]          # 10
                for f in range(Nelec,dim):
                  HSS[ia,kc] += -0.5*(a==c)*ints[k,m,e,f]*td[e,f,i,m]            # 11

shouldn't the second 0.5 term be +? Since psi4 doesn't do eom-mbpt I can't check results against that. Is paper wrong?
            Best Peter

**Comment by pwborthwick** [comment]
Sorry you're correct there's a flip of indexes in a < || > integral I missed. But still some problems with H<sub>SD</sub>. First the H<sub>SS</sub>

From F<sub>ab</sub> equation (25)...
If a->**a**, e->e, m->m, n->n, b->c then &tau;<sup>**a**e</sup><sub>mn</sub> <nm||be> from paper becomes &tau;<sup>**a**e</sup><sub>mn</sub><mn||ce> which agrees with your equation #10, and

from F<sub>ij</sub> equation (26)...
If e->e, f->f, m->m, j->**i**, i->k, then &tau;<sup>ef</sup><sub>mj</sub> <im||ef> from paper becomes &tau;<sup>ef</sup><sub>m**i**</sub><km||ef> but &tau;<sup>ef</sup><sub>m**i**</sub> = -&tau;<sup>ef</sup><sub>**i**m</sub> as definition of &tau; has same symmetry as < || >. As for H<sub>SS</sub>, we are subtracting F<sub>ij</sub> and &tau; term is negative so overall sign is positive and with the sign change for permutation of < || > index then sign is -ve as you have.

For H<sub>SD</sub>, the paper has &Sigma; F<sub>me</sub> + 0.5&Sigma; W<sub>amef</sub> - 0.5&Sigma;W<sub>mnie</sub>  (17). 
You have not included F<sub>me</sub> which is defined as f<sub>me</sub> (27)? OK t<sub>m</sub><sup>a</sup>=0 <=> f<sub>ma</sub>=0 so that's right.
W<sub>amef</sub> = <am||ef> (31) which if a->**a**, m->l, e->c, f->d becomes <**a**,l||c,d> which is consistent with 

                HSD[ia,kcld] += 0.5*ints[a,l,c,d]*(i==k) # 17

W<sub>mnie</sub> = <ni||me> (32) which if n->l, i->**i**, e->d, m->k then becomes <l**i**||kd>. With a definition W<sub>mnie</sub> = <mn||ie> (which is how all other < || > terms are defined for other W-blocks) we would get <kl||id> or -<lk||id> - which is what you have ? This is inconsistent with the definition (32) I think.
            Peter

**Comment by pwborthwick** [comment]
Hi, 
   I'm trying to sort out eom-ccsd I went back to ccsd. I modified the program to read saved S, Hcore and eri from my code (water in sto-3g). This gives an scf energy in pyqchem which agrees with my code and mmd. However the ccsd energy was a bit off in the 5th decimal place. I've checked the ccsd code and found 3 errors in the T2 amplitude code
[1] line 157

	    tdnew[a,b,i,j] += -0.5*td[a,e,i,j]*ts[b,m]*Fme[m,e] + 0.5*td[a,e,i,j]*ts[a,m]*Fme[m,e]
the term td[a,e,i,j] should be td[b,e,i,j] (dimensionally you can see the 2nd expression has no 'b' component)

[2] 

	    tdnew[a,b,i,j] += -0.5*td[a,b,i,m]*ts[e,j]*Fme[m,e] + 0.5*td[a,b,i,m]*ts[e,i]*Fme[m,e]
the term td[a,b,i,m] should be td[a,b,j,m] (dimensionally you can see 2nd expression has no 'j' component)

[3]

	    tdnew[a,b,i,j] += -td[b,e,i,m]*Wmbej[m,a,e,j] - ts[e,i]*ts[b,m]*ints[m,a,e,j]
the sign of the second expression should be +

With these corrections I get **-0.07068009**  which compares to **-0.07068009** from my code and **-0.070680088376** from Crawford (using same geometry). 

I think you know about these typo's but forgot to correct them here, as this code is in the public domain it would be good to correct them when you have time. 

Incidentally I now have found 3 papers which list definitions of F<sub>ab</sub>, 2 have the term -t<sup>a</sup><sub>m</sub>*f*<sub>mb</sub> and 1 with a plus sign. 2 of the papers give W<sub>ijka</sub> = <jk||ia> + t<sup>e</sup><sub>i</sub><jk||ea> and one as W<sub>ijka</sub> = <ij||ka> +  t<sup>e</sup><sub>k</sub><ij||ea> !

     Best wishes,
         Peter

**Comment by pwborthwick** [comment]
Hi @jjgoings ,
   The lines in EOM-CCSD...

                    HDS[iajb,kc] += (i==k)*ts[a,m]*ts[e,i]*ints[m,b,c,e] - \
                                             (i==k)*ts[b,m]*ts[e,i]*ints[m,a,c,e] - \
                                             (j==k)*ts[a,m]*ts[e,j]*ints[m,b,c,e] + \
                                             (j==k)*ts[b,m]*ts[e,j]*ints[m,a,c,e] #38   

(i==k) and (j==k) are on the wrong terms. ie 1st term has no **j**
              Peter

**Comment by jjgoings** [comment]
Hi @pwborthwick!

Thanks for these corrections! Do you mind submitting as a pull request? If you have modified the code to work in a forked version, it is much easier to merge in the corrections versus me trying to eyeball from your comments.

As you realize, this is a very old and unmaintained repo. I have half a thought to just delete the whole thing, but I guess if it has been even somewhat useful for you I'm happy to leave it and incorporate your fixes.

Thanks again -- Josh

**Comment by jjgoings** [comment]
If I recall correctly there is a slight typo for EOM-MBPT2 in the Gwaltney paper you reference, but I forget where. (I do recall it was extremely minor.) The correct equations should be here: https://kuscholarworks.ku.edu/bitstream/handle/1808/21550/Caricato_2014.pdf?sequence=1

**Comment by pwborthwick** [comment]
Hi @jjgoings,
   Yes I see this is old code that you used to play around with EOM/CCSD. I have forked the code and copied bits to test against code I am writing. I'm currently working through the EOM-CCSD equations (from various references and checking against what code I can find). I can correct the fork as I go (I intend to do flavours of EOM-MBPT next) and when I'm finished do a pull request if you like? Seems a shame to delete it all as you obviously put some effort into writing it in the first place. I think in the Gwaltney paper the sign of the t<sup>a</sup><sub>m</sub>F<sub>mb</sub> term is wrong in the F<sub>ab</sub> intermediate.
           Peter

**Comment by jjgoings** [comment]
@pwborthwick Sure! It'd be great to have these fixes in, and a pull request is the best way to do it. You can do it all in one modification, or if you want to do it in two or three chunks, that is fine too. Thanks!

**Comment by pwborthwick** [comment]
Hi @jjgoings ,
    OK. I now agree with all your equations (except one). As I said I had not been careful enough in reading Gwaltney's equations wrongly assuming that the trial vectors were compatible, which fixed my sign differences with the SD block. The differences I got with the DD block were down to changes in the Kronecker deltas I missed. The only outstanding difference now is with #equation 38 where I think the Kronecker deltas are wrong see https://github.com/jjgoings/pyqchem/issues/1#issuecomment-825481554. This should help with the degeneracy problem. I like the integral dump in mmd, I've used Pythons *savez* and *load* to do the same thing, it's a useful feature to have.
 The Gaussian results  are a bit worrying , and given that psi4numpy/Psi4 don't agree (or at least psi4numpy doesn't work) getting a benchmark to test against is a problem at the moment.  Also as I mentioned Psi4 has singlet around 25 eV for H<sub>2</sub> that I don't see in pyqchem, so I'm not 100% sure code is right yet.
I can also now identify all of Hirata equations with one of your numbered equations and they look the same (although Hirata is set up for Davidson type solution). 
   I'm going to close this now but let me know what happens with Gaussian please.
                Peter
